### ISSUE TITLE
return build id as an output variable

### ISSUE THREAD

**Issue by daughey** [bamminger/vsts-queue-build#27]
Using this extension I can queue a build and wait for it to complete.  I would then like to obtain the artifacts of the build I queued.  In theory I could do that with the Download Build Artifacts task for "latest" but in a parallel build world I'd rather give it the precise id of the build I've just waited on.

Therefore, I would like to have the BuildId returned as an output variable on the task.  I can then use it on downstream tasks such as Download Build Artifacts.

Alternatively, having an option to obtain the artifacts from the build it has just waited on would also fulfil that objective but I believe an output variable would be quicker and easier to implement.

**Comment by bamminger** [comment]
Sounds like a good idea.

**Comment by JohnyWS** [comment]
Even better if the id could be customized so I could use a variable on the build definition as input for queue and await tasks. That way I avoid spelling errors and/or renames getting in the way. :)

Currently this is the main reason why we don't use it for our main builds, because there we really need to utilize multiple build agents, and fit the pieces together later on in the same build. I use it without issue on the build definitions where I only need to kick of multiple other builds and not wait for the result. :+1:

**Comment by JohnyWS** [comment]
We use this already with other builds. The following line should just be added:
Write-Host ("##vso[task.setvariable variable=$outputVarName;]$buildId")

(where $outputVarName should contain the name of the variable that should contain the build id, and $buildId should contain the id returned from the API call to TFS)

Without looking a lot deeper into the code, I don't know where to add the configuration part of it though, because, if it should continue supporting multiple builds/configs, the output variable name should probably also be configureable.

**Comment by bamminger** [comment]
Sorry for the delay. Had no time to implement it yet. I've scheduled it for the weekend.
Current plan is to make an input field which defines the name of the output variable. In addition it will be possible to define it per build.

**Comment by bamminger** [comment]
Finally implemented.
First way of defining the output variable is the input field in the [Advanced Group](https://github.com/bamminger/vsts-queue-build/blob/master/README.md#settings).
In addition to that it is possible to define it per build via the [configuration field](
https://github.com/bamminger/vsts-queue-build/blob/master/doc/configuration.md#configuration)
Multiple builds will be concatenated with a comma into the output variable.
